/*
 * Thumbnails Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.Roblox.Thumbnails.ApiV1.Model;
using Knedlex.Roblox.Thumbnails.ApiV1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.Roblox.Thumbnails.ApiV1.Test.Model
{
    /// <summary>
    ///  Class for testing RobloxWebResponsesThumbnailsThumbnailBatchResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RobloxWebResponsesThumbnailsThumbnailBatchResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RobloxWebResponsesThumbnailsThumbnailBatchResponse
        //private RobloxWebResponsesThumbnailsThumbnailBatchResponse instance;

        public RobloxWebResponsesThumbnailsThumbnailBatchResponseTests()
        {
            // TODO uncomment below to create an instance of RobloxWebResponsesThumbnailsThumbnailBatchResponse
            //instance = new RobloxWebResponsesThumbnailsThumbnailBatchResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RobloxWebResponsesThumbnailsThumbnailBatchResponse
        /// </summary>
        [Fact]
        public void RobloxWebResponsesThumbnailsThumbnailBatchResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" RobloxWebResponsesThumbnailsThumbnailBatchResponse
            //Assert.IsType<RobloxWebResponsesThumbnailsThumbnailBatchResponse>(instance);
        }

        /// <summary>
        /// Test the property 'RequestId'
        /// </summary>
        [Fact]
        public void RequestIdTest()
        {
            // TODO unit test for the property 'RequestId'
        }

        /// <summary>
        /// Test the property 'ErrorCode'
        /// </summary>
        [Fact]
        public void ErrorCodeTest()
        {
            // TODO unit test for the property 'ErrorCode'
        }

        /// <summary>
        /// Test the property 'ErrorMessage'
        /// </summary>
        [Fact]
        public void ErrorMessageTest()
        {
            // TODO unit test for the property 'ErrorMessage'
        }

        /// <summary>
        /// Test the property 'TargetId'
        /// </summary>
        [Fact]
        public void TargetIdTest()
        {
            // TODO unit test for the property 'TargetId'
        }

        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }

        /// <summary>
        /// Test the property 'ImageUrl'
        /// </summary>
        [Fact]
        public void ImageUrlTest()
        {
            // TODO unit test for the property 'ImageUrl'
        }

        /// <summary>
        /// Test the property 'VarVersion'
        /// </summary>
        [Fact]
        public void VarVersionTest()
        {
            // TODO unit test for the property 'VarVersion'
        }
    }
}
