/*
 * Thumbnails Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.Roblox.Thumbnails.ApiV1.Model;
using Knedlex.Roblox.Thumbnails.ApiV1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.Roblox.Thumbnails.ApiV1.Test.Model
{
    /// <summary>
    ///  Class for testing RobloxThumbnailsApiModelsUniverseThumbnailsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RobloxThumbnailsApiModelsUniverseThumbnailsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RobloxThumbnailsApiModelsUniverseThumbnailsResponse
        //private RobloxThumbnailsApiModelsUniverseThumbnailsResponse instance;

        public RobloxThumbnailsApiModelsUniverseThumbnailsResponseTests()
        {
            // TODO uncomment below to create an instance of RobloxThumbnailsApiModelsUniverseThumbnailsResponse
            //instance = new RobloxThumbnailsApiModelsUniverseThumbnailsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RobloxThumbnailsApiModelsUniverseThumbnailsResponse
        /// </summary>
        [Fact]
        public void RobloxThumbnailsApiModelsUniverseThumbnailsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" RobloxThumbnailsApiModelsUniverseThumbnailsResponse
            //Assert.IsType<RobloxThumbnailsApiModelsUniverseThumbnailsResponse>(instance);
        }

        /// <summary>
        /// Test the property 'UniverseId'
        /// </summary>
        [Fact]
        public void UniverseIdTest()
        {
            // TODO unit test for the property 'UniverseId'
        }

        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }

        /// <summary>
        /// Test the property 'Thumbnails'
        /// </summary>
        [Fact]
        public void ThumbnailsTest()
        {
            // TODO unit test for the property 'Thumbnails'
        }
    }
}
