/*
 * Thumbnails Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.Roblox.Thumbnails.ApiV1.Model;
using Knedlex.Roblox.Thumbnails.ApiV1.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.Roblox.Thumbnails.ApiV1.Test.Model
{
    /// <summary>
    ///  Class for testing RobloxThumbnailsApisModelsThumbnailBatchRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RobloxThumbnailsApisModelsThumbnailBatchRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RobloxThumbnailsApisModelsThumbnailBatchRequest
        //private RobloxThumbnailsApisModelsThumbnailBatchRequest instance;

        public RobloxThumbnailsApisModelsThumbnailBatchRequestTests()
        {
            // TODO uncomment below to create an instance of RobloxThumbnailsApisModelsThumbnailBatchRequest
            //instance = new RobloxThumbnailsApisModelsThumbnailBatchRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RobloxThumbnailsApisModelsThumbnailBatchRequest
        /// </summary>
        [Fact]
        public void RobloxThumbnailsApisModelsThumbnailBatchRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" RobloxThumbnailsApisModelsThumbnailBatchRequest
            //Assert.IsType<RobloxThumbnailsApisModelsThumbnailBatchRequest>(instance);
        }

        /// <summary>
        /// Test the property 'RequestId'
        /// </summary>
        [Fact]
        public void RequestIdTest()
        {
            // TODO unit test for the property 'RequestId'
        }

        /// <summary>
        /// Test the property 'TargetId'
        /// </summary>
        [Fact]
        public void TargetIdTest()
        {
            // TODO unit test for the property 'TargetId'
        }

        /// <summary>
        /// Test the property 'Token'
        /// </summary>
        [Fact]
        public void TokenTest()
        {
            // TODO unit test for the property 'Token'
        }

        /// <summary>
        /// Test the property 'Alias'
        /// </summary>
        [Fact]
        public void AliasTest()
        {
            // TODO unit test for the property 'Alias'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Fact]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }

        /// <summary>
        /// Test the property 'Format'
        /// </summary>
        [Fact]
        public void FormatTest()
        {
            // TODO unit test for the property 'Format'
        }

        /// <summary>
        /// Test the property 'IsCircular'
        /// </summary>
        [Fact]
        public void IsCircularTest()
        {
            // TODO unit test for the property 'IsCircular'
        }
    }
}
