/*
 * Thumbnails Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Knedlex.Roblox.Thumbnails.Api.Client;
using Knedlex.Roblox.Thumbnails.Api.Model;

namespace Knedlex.Roblox.Thumbnails.Api.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IGamesApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Fetches game icon URLs for a list of universes&#39; root places. Ids that do not correspond to a valid universe will be filtered out.
        /// </summary>
        /// <exception cref="Knedlex.Roblox.Thumbnails.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="universeIds">The universe ids.</param>
        /// <param name="returnPolicy">Optional policy to use in selecting game icon to return (default &#x3D; PlaceHolder). (optional, default to PlaceHolder)</param>
        /// <param name="size">The thumbnail size, formatted widthxheight (optional, default to 50x50)</param>
        /// <param name="format">The thumbnail format (optional, default to Png)</param>
        /// <param name="isCircular">The circle thumbnail output parameter, true or false (optional, default to false)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>RobloxWebWebAPIModelsApiArrayResponseRobloxWebResponsesThumbnailsThumbnailResponse</returns>
        RobloxWebWebAPIModelsApiArrayResponseRobloxWebResponsesThumbnailsThumbnailResponse V1GamesIconsGet(List<long> universeIds, string returnPolicy = default(string), string size = default(string), string format = default(string), bool? isCircular = default(bool?), int operationIndex = 0);

        /// <summary>
        /// Fetches game icon URLs for a list of universes&#39; root places. Ids that do not correspond to a valid universe will be filtered out.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Knedlex.Roblox.Thumbnails.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="universeIds">The universe ids.</param>
        /// <param name="returnPolicy">Optional policy to use in selecting game icon to return (default &#x3D; PlaceHolder). (optional, default to PlaceHolder)</param>
        /// <param name="size">The thumbnail size, formatted widthxheight (optional, default to 50x50)</param>
        /// <param name="format">The thumbnail format (optional, default to Png)</param>
        /// <param name="isCircular">The circle thumbnail output parameter, true or false (optional, default to false)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of RobloxWebWebAPIModelsApiArrayResponseRobloxWebResponsesThumbnailsThumbnailResponse</returns>
        ApiResponse<RobloxWebWebAPIModelsApiArrayResponseRobloxWebResponsesThumbnailsThumbnailResponse> V1GamesIconsGetWithHttpInfo(List<long> universeIds, string returnPolicy = default(string), string size = default(string), string format = default(string), bool? isCircular = default(bool?), int operationIndex = 0);
        /// <summary>
        /// Fetch game thumbnail URLs for a list of universe IDs.
        /// </summary>
        /// <exception cref="Knedlex.Roblox.Thumbnails.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="universeIds">comma-delimited list of universe IDs</param>
        /// <param name="countPerUniverse">max number of thumbnails to return per universe (optional, default to 1)</param>
        /// <param name="defaults">true if defaults (if any) should be returned if no media exists (optional, default to true)</param>
        /// <param name="size">The thumbnail size, formatted widthxheight (optional, default to 768x432)</param>
        /// <param name="format">The thumbnail format (optional, default to Png)</param>
        /// <param name="isCircular">The circle thumbnail output parameter, true or false (optional, default to false)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>RobloxWebWebAPIModelsApiArrayResponseRobloxThumbnailsApiModelsUniverseThumbnailsResponse</returns>
        RobloxWebWebAPIModelsApiArrayResponseRobloxThumbnailsApiModelsUniverseThumbnailsResponse V1GamesMultigetThumbnailsGet(List<long> universeIds, int? countPerUniverse = default(int?), bool? defaults = default(bool?), string size = default(string), string format = default(string), bool? isCircular = default(bool?), int operationIndex = 0);

        /// <summary>
        /// Fetch game thumbnail URLs for a list of universe IDs.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Knedlex.Roblox.Thumbnails.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="universeIds">comma-delimited list of universe IDs</param>
        /// <param name="countPerUniverse">max number of thumbnails to return per universe (optional, default to 1)</param>
        /// <param name="defaults">true if defaults (if any) should be returned if no media exists (optional, default to true)</param>
        /// <param name="size">The thumbnail size, formatted widthxheight (optional, default to 768x432)</param>
        /// <param name="format">The thumbnail format (optional, default to Png)</param>
        /// <param name="isCircular">The circle thumbnail output parameter, true or false (optional, default to false)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of RobloxWebWebAPIModelsApiArrayResponseRobloxThumbnailsApiModelsUniverseThumbnailsResponse</returns>
        ApiResponse<RobloxWebWebAPIModelsApiArrayResponseRobloxThumbnailsApiModelsUniverseThumbnailsResponse> V1GamesMultigetThumbnailsGetWithHttpInfo(List<long> universeIds, int? countPerUniverse = default(int?), bool? defaults = default(bool?), string size = default(string), string format = default(string), bool? isCircular = default(bool?), int operationIndex = 0);
        /// <summary>
        /// Fetches game thumbnail URLs for a list of universes&#39; thumbnail ids. Ids that do not correspond to a valid thumbnail will be filtered out.
        /// </summary>
        /// <exception cref="Knedlex.Roblox.Thumbnails.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="universeId"></param>
        /// <param name="thumbnailIds"></param>
        /// <param name="size">The thumbnail size, formatted widthxheight (optional, default to 768x432)</param>
        /// <param name="format">The thumbnail format (optional, default to Png)</param>
        /// <param name="isCircular">The circle thumbnail output parameter, true or false (optional, default to false)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>RobloxWebWebAPIModelsApiArrayResponseRobloxWebResponsesThumbnailsThumbnailResponse</returns>
        RobloxWebWebAPIModelsApiArrayResponseRobloxWebResponsesThumbnailsThumbnailResponse V1GamesUniverseIdThumbnailsGet(long universeId, List<long> thumbnailIds, string size = default(string), string format = default(string), bool? isCircular = default(bool?), int operationIndex = 0);

        /// <summary>
        /// Fetches game thumbnail URLs for a list of universes&#39; thumbnail ids. Ids that do not correspond to a valid thumbnail will be filtered out.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Knedlex.Roblox.Thumbnails.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="universeId"></param>
        /// <param name="thumbnailIds"></param>
        /// <param name="size">The thumbnail size, formatted widthxheight (optional, default to 768x432)</param>
        /// <param name="format">The thumbnail format (optional, default to Png)</param>
        /// <param name="isCircular">The circle thumbnail output parameter, true or false (optional, default to false)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of RobloxWebWebAPIModelsApiArrayResponseRobloxWebResponsesThumbnailsThumbnailResponse</returns>
        ApiResponse<RobloxWebWebAPIModelsApiArrayResponseRobloxWebResponsesThumbnailsThumbnailResponse> V1GamesUniverseIdThumbnailsGetWithHttpInfo(long universeId, List<long> thumbnailIds, string size = default(string), string format = default(string), bool? isCircular = default(bool?), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IGamesApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Fetches game icon URLs for a list of universes&#39; root places. Ids that do not correspond to a valid universe will be filtered out.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Knedlex.Roblox.Thumbnails.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="universeIds">The universe ids.</param>
        /// <param name="returnPolicy">Optional policy to use in selecting game icon to return (default &#x3D; PlaceHolder). (optional, default to PlaceHolder)</param>
        /// <param name="size">The thumbnail size, formatted widthxheight (optional, default to 50x50)</param>
        /// <param name="format">The thumbnail format (optional, default to Png)</param>
        /// <param name="isCircular">The circle thumbnail output parameter, true or false (optional, default to false)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of RobloxWebWebAPIModelsApiArrayResponseRobloxWebResponsesThumbnailsThumbnailResponse</returns>
        System.Threading.Tasks.Task<RobloxWebWebAPIModelsApiArrayResponseRobloxWebResponsesThumbnailsThumbnailResponse> V1GamesIconsGetAsync(List<long> universeIds, string returnPolicy = default(string), string size = default(string), string format = default(string), bool? isCircular = default(bool?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Fetches game icon URLs for a list of universes&#39; root places. Ids that do not correspond to a valid universe will be filtered out.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Knedlex.Roblox.Thumbnails.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="universeIds">The universe ids.</param>
        /// <param name="returnPolicy">Optional policy to use in selecting game icon to return (default &#x3D; PlaceHolder). (optional, default to PlaceHolder)</param>
        /// <param name="size">The thumbnail size, formatted widthxheight (optional, default to 50x50)</param>
        /// <param name="format">The thumbnail format (optional, default to Png)</param>
        /// <param name="isCircular">The circle thumbnail output parameter, true or false (optional, default to false)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (RobloxWebWebAPIModelsApiArrayResponseRobloxWebResponsesThumbnailsThumbnailResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<RobloxWebWebAPIModelsApiArrayResponseRobloxWebResponsesThumbnailsThumbnailResponse>> V1GamesIconsGetWithHttpInfoAsync(List<long> universeIds, string returnPolicy = default(string), string size = default(string), string format = default(string), bool? isCircular = default(bool?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Fetch game thumbnail URLs for a list of universe IDs.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Knedlex.Roblox.Thumbnails.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="universeIds">comma-delimited list of universe IDs</param>
        /// <param name="countPerUniverse">max number of thumbnails to return per universe (optional, default to 1)</param>
        /// <param name="defaults">true if defaults (if any) should be returned if no media exists (optional, default to true)</param>
        /// <param name="size">The thumbnail size, formatted widthxheight (optional, default to 768x432)</param>
        /// <param name="format">The thumbnail format (optional, default to Png)</param>
        /// <param name="isCircular">The circle thumbnail output parameter, true or false (optional, default to false)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of RobloxWebWebAPIModelsApiArrayResponseRobloxThumbnailsApiModelsUniverseThumbnailsResponse</returns>
        System.Threading.Tasks.Task<RobloxWebWebAPIModelsApiArrayResponseRobloxThumbnailsApiModelsUniverseThumbnailsResponse> V1GamesMultigetThumbnailsGetAsync(List<long> universeIds, int? countPerUniverse = default(int?), bool? defaults = default(bool?), string size = default(string), string format = default(string), bool? isCircular = default(bool?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Fetch game thumbnail URLs for a list of universe IDs.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Knedlex.Roblox.Thumbnails.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="universeIds">comma-delimited list of universe IDs</param>
        /// <param name="countPerUniverse">max number of thumbnails to return per universe (optional, default to 1)</param>
        /// <param name="defaults">true if defaults (if any) should be returned if no media exists (optional, default to true)</param>
        /// <param name="size">The thumbnail size, formatted widthxheight (optional, default to 768x432)</param>
        /// <param name="format">The thumbnail format (optional, default to Png)</param>
        /// <param name="isCircular">The circle thumbnail output parameter, true or false (optional, default to false)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (RobloxWebWebAPIModelsApiArrayResponseRobloxThumbnailsApiModelsUniverseThumbnailsResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<RobloxWebWebAPIModelsApiArrayResponseRobloxThumbnailsApiModelsUniverseThumbnailsResponse>> V1GamesMultigetThumbnailsGetWithHttpInfoAsync(List<long> universeIds, int? countPerUniverse = default(int?), bool? defaults = default(bool?), string size = default(string), string format = default(string), bool? isCircular = default(bool?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Fetches game thumbnail URLs for a list of universes&#39; thumbnail ids. Ids that do not correspond to a valid thumbnail will be filtered out.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Knedlex.Roblox.Thumbnails.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="universeId"></param>
        /// <param name="thumbnailIds"></param>
        /// <param name="size">The thumbnail size, formatted widthxheight (optional, default to 768x432)</param>
        /// <param name="format">The thumbnail format (optional, default to Png)</param>
        /// <param name="isCircular">The circle thumbnail output parameter, true or false (optional, default to false)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of RobloxWebWebAPIModelsApiArrayResponseRobloxWebResponsesThumbnailsThumbnailResponse</returns>
        System.Threading.Tasks.Task<RobloxWebWebAPIModelsApiArrayResponseRobloxWebResponsesThumbnailsThumbnailResponse> V1GamesUniverseIdThumbnailsGetAsync(long universeId, List<long> thumbnailIds, string size = default(string), string format = default(string), bool? isCircular = default(bool?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Fetches game thumbnail URLs for a list of universes&#39; thumbnail ids. Ids that do not correspond to a valid thumbnail will be filtered out.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Knedlex.Roblox.Thumbnails.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="universeId"></param>
        /// <param name="thumbnailIds"></param>
        /// <param name="size">The thumbnail size, formatted widthxheight (optional, default to 768x432)</param>
        /// <param name="format">The thumbnail format (optional, default to Png)</param>
        /// <param name="isCircular">The circle thumbnail output parameter, true or false (optional, default to false)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (RobloxWebWebAPIModelsApiArrayResponseRobloxWebResponsesThumbnailsThumbnailResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<RobloxWebWebAPIModelsApiArrayResponseRobloxWebResponsesThumbnailsThumbnailResponse>> V1GamesUniverseIdThumbnailsGetWithHttpInfoAsync(long universeId, List<long> thumbnailIds, string size = default(string), string format = default(string), bool? isCircular = default(bool?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IGamesApi : IGamesApiSync, IGamesApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class GamesApi : IGamesApi
    {
        private Knedlex.Roblox.Thumbnails.Api.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="GamesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public GamesApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GamesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public GamesApi(string basePath)
        {
            this.Configuration = Knedlex.Roblox.Thumbnails.Api.Client.Configuration.MergeConfigurations(
                Knedlex.Roblox.Thumbnails.Api.Client.GlobalConfiguration.Instance,
                new Knedlex.Roblox.Thumbnails.Api.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Knedlex.Roblox.Thumbnails.Api.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Knedlex.Roblox.Thumbnails.Api.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Knedlex.Roblox.Thumbnails.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GamesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public GamesApi(Knedlex.Roblox.Thumbnails.Api.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Knedlex.Roblox.Thumbnails.Api.Client.Configuration.MergeConfigurations(
                Knedlex.Roblox.Thumbnails.Api.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Knedlex.Roblox.Thumbnails.Api.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Knedlex.Roblox.Thumbnails.Api.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Knedlex.Roblox.Thumbnails.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GamesApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public GamesApi(Knedlex.Roblox.Thumbnails.Api.Client.ISynchronousClient client, Knedlex.Roblox.Thumbnails.Api.Client.IAsynchronousClient asyncClient, Knedlex.Roblox.Thumbnails.Api.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Knedlex.Roblox.Thumbnails.Api.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Knedlex.Roblox.Thumbnails.Api.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Knedlex.Roblox.Thumbnails.Api.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Knedlex.Roblox.Thumbnails.Api.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Knedlex.Roblox.Thumbnails.Api.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Fetches game icon URLs for a list of universes&#39; root places. Ids that do not correspond to a valid universe will be filtered out. 
        /// </summary>
        /// <exception cref="Knedlex.Roblox.Thumbnails.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="universeIds">The universe ids.</param>
        /// <param name="returnPolicy">Optional policy to use in selecting game icon to return (default &#x3D; PlaceHolder). (optional, default to PlaceHolder)</param>
        /// <param name="size">The thumbnail size, formatted widthxheight (optional, default to 50x50)</param>
        /// <param name="format">The thumbnail format (optional, default to Png)</param>
        /// <param name="isCircular">The circle thumbnail output parameter, true or false (optional, default to false)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>RobloxWebWebAPIModelsApiArrayResponseRobloxWebResponsesThumbnailsThumbnailResponse</returns>
        public RobloxWebWebAPIModelsApiArrayResponseRobloxWebResponsesThumbnailsThumbnailResponse V1GamesIconsGet(List<long> universeIds, string returnPolicy = default(string), string size = default(string), string format = default(string), bool? isCircular = default(bool?), int operationIndex = 0)
        {
            Knedlex.Roblox.Thumbnails.Api.Client.ApiResponse<RobloxWebWebAPIModelsApiArrayResponseRobloxWebResponsesThumbnailsThumbnailResponse> localVarResponse = V1GamesIconsGetWithHttpInfo(universeIds, returnPolicy, size, format, isCircular);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Fetches game icon URLs for a list of universes&#39; root places. Ids that do not correspond to a valid universe will be filtered out. 
        /// </summary>
        /// <exception cref="Knedlex.Roblox.Thumbnails.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="universeIds">The universe ids.</param>
        /// <param name="returnPolicy">Optional policy to use in selecting game icon to return (default &#x3D; PlaceHolder). (optional, default to PlaceHolder)</param>
        /// <param name="size">The thumbnail size, formatted widthxheight (optional, default to 50x50)</param>
        /// <param name="format">The thumbnail format (optional, default to Png)</param>
        /// <param name="isCircular">The circle thumbnail output parameter, true or false (optional, default to false)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of RobloxWebWebAPIModelsApiArrayResponseRobloxWebResponsesThumbnailsThumbnailResponse</returns>
        public Knedlex.Roblox.Thumbnails.Api.Client.ApiResponse<RobloxWebWebAPIModelsApiArrayResponseRobloxWebResponsesThumbnailsThumbnailResponse> V1GamesIconsGetWithHttpInfo(List<long> universeIds, string returnPolicy = default(string), string size = default(string), string format = default(string), bool? isCircular = default(bool?), int operationIndex = 0)
        {
            // verify the required parameter 'universeIds' is set
            if (universeIds == null)
            {
                throw new Knedlex.Roblox.Thumbnails.Api.Client.ApiException(400, "Missing required parameter 'universeIds' when calling GamesApi->V1GamesIconsGet");
            }

            Knedlex.Roblox.Thumbnails.Api.Client.RequestOptions localVarRequestOptions = new Knedlex.Roblox.Thumbnails.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "text/json"
            };

            var localVarContentType = Knedlex.Roblox.Thumbnails.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Knedlex.Roblox.Thumbnails.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.QueryParameters.Add(Knedlex.Roblox.Thumbnails.Api.Client.ClientUtils.ParameterToMultiMap("csv", "universeIds", universeIds));
            if (returnPolicy != null)
            {
                localVarRequestOptions.QueryParameters.Add(Knedlex.Roblox.Thumbnails.Api.Client.ClientUtils.ParameterToMultiMap("", "returnPolicy", returnPolicy));
            }
            if (size != null)
            {
                localVarRequestOptions.QueryParameters.Add(Knedlex.Roblox.Thumbnails.Api.Client.ClientUtils.ParameterToMultiMap("", "size", size));
            }
            if (format != null)
            {
                localVarRequestOptions.QueryParameters.Add(Knedlex.Roblox.Thumbnails.Api.Client.ClientUtils.ParameterToMultiMap("", "format", format));
            }
            if (isCircular != null)
            {
                localVarRequestOptions.QueryParameters.Add(Knedlex.Roblox.Thumbnails.Api.Client.ClientUtils.ParameterToMultiMap("", "isCircular", isCircular));
            }

            localVarRequestOptions.Operation = "GamesApi.V1GamesIconsGet";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<RobloxWebWebAPIModelsApiArrayResponseRobloxWebResponsesThumbnailsThumbnailResponse>("/v1/games/icons", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("V1GamesIconsGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Fetches game icon URLs for a list of universes&#39; root places. Ids that do not correspond to a valid universe will be filtered out. 
        /// </summary>
        /// <exception cref="Knedlex.Roblox.Thumbnails.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="universeIds">The universe ids.</param>
        /// <param name="returnPolicy">Optional policy to use in selecting game icon to return (default &#x3D; PlaceHolder). (optional, default to PlaceHolder)</param>
        /// <param name="size">The thumbnail size, formatted widthxheight (optional, default to 50x50)</param>
        /// <param name="format">The thumbnail format (optional, default to Png)</param>
        /// <param name="isCircular">The circle thumbnail output parameter, true or false (optional, default to false)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of RobloxWebWebAPIModelsApiArrayResponseRobloxWebResponsesThumbnailsThumbnailResponse</returns>
        public async System.Threading.Tasks.Task<RobloxWebWebAPIModelsApiArrayResponseRobloxWebResponsesThumbnailsThumbnailResponse> V1GamesIconsGetAsync(List<long> universeIds, string returnPolicy = default(string), string size = default(string), string format = default(string), bool? isCircular = default(bool?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Knedlex.Roblox.Thumbnails.Api.Client.ApiResponse<RobloxWebWebAPIModelsApiArrayResponseRobloxWebResponsesThumbnailsThumbnailResponse> localVarResponse = await V1GamesIconsGetWithHttpInfoAsync(universeIds, returnPolicy, size, format, isCircular, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Fetches game icon URLs for a list of universes&#39; root places. Ids that do not correspond to a valid universe will be filtered out. 
        /// </summary>
        /// <exception cref="Knedlex.Roblox.Thumbnails.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="universeIds">The universe ids.</param>
        /// <param name="returnPolicy">Optional policy to use in selecting game icon to return (default &#x3D; PlaceHolder). (optional, default to PlaceHolder)</param>
        /// <param name="size">The thumbnail size, formatted widthxheight (optional, default to 50x50)</param>
        /// <param name="format">The thumbnail format (optional, default to Png)</param>
        /// <param name="isCircular">The circle thumbnail output parameter, true or false (optional, default to false)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (RobloxWebWebAPIModelsApiArrayResponseRobloxWebResponsesThumbnailsThumbnailResponse)</returns>
        public async System.Threading.Tasks.Task<Knedlex.Roblox.Thumbnails.Api.Client.ApiResponse<RobloxWebWebAPIModelsApiArrayResponseRobloxWebResponsesThumbnailsThumbnailResponse>> V1GamesIconsGetWithHttpInfoAsync(List<long> universeIds, string returnPolicy = default(string), string size = default(string), string format = default(string), bool? isCircular = default(bool?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'universeIds' is set
            if (universeIds == null)
            {
                throw new Knedlex.Roblox.Thumbnails.Api.Client.ApiException(400, "Missing required parameter 'universeIds' when calling GamesApi->V1GamesIconsGet");
            }


            Knedlex.Roblox.Thumbnails.Api.Client.RequestOptions localVarRequestOptions = new Knedlex.Roblox.Thumbnails.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "text/json"
            };

            var localVarContentType = Knedlex.Roblox.Thumbnails.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Knedlex.Roblox.Thumbnails.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.QueryParameters.Add(Knedlex.Roblox.Thumbnails.Api.Client.ClientUtils.ParameterToMultiMap("csv", "universeIds", universeIds));
            if (returnPolicy != null)
            {
                localVarRequestOptions.QueryParameters.Add(Knedlex.Roblox.Thumbnails.Api.Client.ClientUtils.ParameterToMultiMap("", "returnPolicy", returnPolicy));
            }
            if (size != null)
            {
                localVarRequestOptions.QueryParameters.Add(Knedlex.Roblox.Thumbnails.Api.Client.ClientUtils.ParameterToMultiMap("", "size", size));
            }
            if (format != null)
            {
                localVarRequestOptions.QueryParameters.Add(Knedlex.Roblox.Thumbnails.Api.Client.ClientUtils.ParameterToMultiMap("", "format", format));
            }
            if (isCircular != null)
            {
                localVarRequestOptions.QueryParameters.Add(Knedlex.Roblox.Thumbnails.Api.Client.ClientUtils.ParameterToMultiMap("", "isCircular", isCircular));
            }

            localVarRequestOptions.Operation = "GamesApi.V1GamesIconsGet";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<RobloxWebWebAPIModelsApiArrayResponseRobloxWebResponsesThumbnailsThumbnailResponse>("/v1/games/icons", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("V1GamesIconsGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Fetch game thumbnail URLs for a list of universe IDs. 
        /// </summary>
        /// <exception cref="Knedlex.Roblox.Thumbnails.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="universeIds">comma-delimited list of universe IDs</param>
        /// <param name="countPerUniverse">max number of thumbnails to return per universe (optional, default to 1)</param>
        /// <param name="defaults">true if defaults (if any) should be returned if no media exists (optional, default to true)</param>
        /// <param name="size">The thumbnail size, formatted widthxheight (optional, default to 768x432)</param>
        /// <param name="format">The thumbnail format (optional, default to Png)</param>
        /// <param name="isCircular">The circle thumbnail output parameter, true or false (optional, default to false)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>RobloxWebWebAPIModelsApiArrayResponseRobloxThumbnailsApiModelsUniverseThumbnailsResponse</returns>
        public RobloxWebWebAPIModelsApiArrayResponseRobloxThumbnailsApiModelsUniverseThumbnailsResponse V1GamesMultigetThumbnailsGet(List<long> universeIds, int? countPerUniverse = default(int?), bool? defaults = default(bool?), string size = default(string), string format = default(string), bool? isCircular = default(bool?), int operationIndex = 0)
        {
            Knedlex.Roblox.Thumbnails.Api.Client.ApiResponse<RobloxWebWebAPIModelsApiArrayResponseRobloxThumbnailsApiModelsUniverseThumbnailsResponse> localVarResponse = V1GamesMultigetThumbnailsGetWithHttpInfo(universeIds, countPerUniverse, defaults, size, format, isCircular);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Fetch game thumbnail URLs for a list of universe IDs. 
        /// </summary>
        /// <exception cref="Knedlex.Roblox.Thumbnails.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="universeIds">comma-delimited list of universe IDs</param>
        /// <param name="countPerUniverse">max number of thumbnails to return per universe (optional, default to 1)</param>
        /// <param name="defaults">true if defaults (if any) should be returned if no media exists (optional, default to true)</param>
        /// <param name="size">The thumbnail size, formatted widthxheight (optional, default to 768x432)</param>
        /// <param name="format">The thumbnail format (optional, default to Png)</param>
        /// <param name="isCircular">The circle thumbnail output parameter, true or false (optional, default to false)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of RobloxWebWebAPIModelsApiArrayResponseRobloxThumbnailsApiModelsUniverseThumbnailsResponse</returns>
        public Knedlex.Roblox.Thumbnails.Api.Client.ApiResponse<RobloxWebWebAPIModelsApiArrayResponseRobloxThumbnailsApiModelsUniverseThumbnailsResponse> V1GamesMultigetThumbnailsGetWithHttpInfo(List<long> universeIds, int? countPerUniverse = default(int?), bool? defaults = default(bool?), string size = default(string), string format = default(string), bool? isCircular = default(bool?), int operationIndex = 0)
        {
            // verify the required parameter 'universeIds' is set
            if (universeIds == null)
            {
                throw new Knedlex.Roblox.Thumbnails.Api.Client.ApiException(400, "Missing required parameter 'universeIds' when calling GamesApi->V1GamesMultigetThumbnailsGet");
            }

            Knedlex.Roblox.Thumbnails.Api.Client.RequestOptions localVarRequestOptions = new Knedlex.Roblox.Thumbnails.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "text/json"
            };

            var localVarContentType = Knedlex.Roblox.Thumbnails.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Knedlex.Roblox.Thumbnails.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.QueryParameters.Add(Knedlex.Roblox.Thumbnails.Api.Client.ClientUtils.ParameterToMultiMap("csv", "universeIds", universeIds));
            if (countPerUniverse != null)
            {
                localVarRequestOptions.QueryParameters.Add(Knedlex.Roblox.Thumbnails.Api.Client.ClientUtils.ParameterToMultiMap("", "countPerUniverse", countPerUniverse));
            }
            if (defaults != null)
            {
                localVarRequestOptions.QueryParameters.Add(Knedlex.Roblox.Thumbnails.Api.Client.ClientUtils.ParameterToMultiMap("", "defaults", defaults));
            }
            if (size != null)
            {
                localVarRequestOptions.QueryParameters.Add(Knedlex.Roblox.Thumbnails.Api.Client.ClientUtils.ParameterToMultiMap("", "size", size));
            }
            if (format != null)
            {
                localVarRequestOptions.QueryParameters.Add(Knedlex.Roblox.Thumbnails.Api.Client.ClientUtils.ParameterToMultiMap("", "format", format));
            }
            if (isCircular != null)
            {
                localVarRequestOptions.QueryParameters.Add(Knedlex.Roblox.Thumbnails.Api.Client.ClientUtils.ParameterToMultiMap("", "isCircular", isCircular));
            }

            localVarRequestOptions.Operation = "GamesApi.V1GamesMultigetThumbnailsGet";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<RobloxWebWebAPIModelsApiArrayResponseRobloxThumbnailsApiModelsUniverseThumbnailsResponse>("/v1/games/multiget/thumbnails", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("V1GamesMultigetThumbnailsGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Fetch game thumbnail URLs for a list of universe IDs. 
        /// </summary>
        /// <exception cref="Knedlex.Roblox.Thumbnails.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="universeIds">comma-delimited list of universe IDs</param>
        /// <param name="countPerUniverse">max number of thumbnails to return per universe (optional, default to 1)</param>
        /// <param name="defaults">true if defaults (if any) should be returned if no media exists (optional, default to true)</param>
        /// <param name="size">The thumbnail size, formatted widthxheight (optional, default to 768x432)</param>
        /// <param name="format">The thumbnail format (optional, default to Png)</param>
        /// <param name="isCircular">The circle thumbnail output parameter, true or false (optional, default to false)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of RobloxWebWebAPIModelsApiArrayResponseRobloxThumbnailsApiModelsUniverseThumbnailsResponse</returns>
        public async System.Threading.Tasks.Task<RobloxWebWebAPIModelsApiArrayResponseRobloxThumbnailsApiModelsUniverseThumbnailsResponse> V1GamesMultigetThumbnailsGetAsync(List<long> universeIds, int? countPerUniverse = default(int?), bool? defaults = default(bool?), string size = default(string), string format = default(string), bool? isCircular = default(bool?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Knedlex.Roblox.Thumbnails.Api.Client.ApiResponse<RobloxWebWebAPIModelsApiArrayResponseRobloxThumbnailsApiModelsUniverseThumbnailsResponse> localVarResponse = await V1GamesMultigetThumbnailsGetWithHttpInfoAsync(universeIds, countPerUniverse, defaults, size, format, isCircular, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Fetch game thumbnail URLs for a list of universe IDs. 
        /// </summary>
        /// <exception cref="Knedlex.Roblox.Thumbnails.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="universeIds">comma-delimited list of universe IDs</param>
        /// <param name="countPerUniverse">max number of thumbnails to return per universe (optional, default to 1)</param>
        /// <param name="defaults">true if defaults (if any) should be returned if no media exists (optional, default to true)</param>
        /// <param name="size">The thumbnail size, formatted widthxheight (optional, default to 768x432)</param>
        /// <param name="format">The thumbnail format (optional, default to Png)</param>
        /// <param name="isCircular">The circle thumbnail output parameter, true or false (optional, default to false)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (RobloxWebWebAPIModelsApiArrayResponseRobloxThumbnailsApiModelsUniverseThumbnailsResponse)</returns>
        public async System.Threading.Tasks.Task<Knedlex.Roblox.Thumbnails.Api.Client.ApiResponse<RobloxWebWebAPIModelsApiArrayResponseRobloxThumbnailsApiModelsUniverseThumbnailsResponse>> V1GamesMultigetThumbnailsGetWithHttpInfoAsync(List<long> universeIds, int? countPerUniverse = default(int?), bool? defaults = default(bool?), string size = default(string), string format = default(string), bool? isCircular = default(bool?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'universeIds' is set
            if (universeIds == null)
            {
                throw new Knedlex.Roblox.Thumbnails.Api.Client.ApiException(400, "Missing required parameter 'universeIds' when calling GamesApi->V1GamesMultigetThumbnailsGet");
            }


            Knedlex.Roblox.Thumbnails.Api.Client.RequestOptions localVarRequestOptions = new Knedlex.Roblox.Thumbnails.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "text/json"
            };

            var localVarContentType = Knedlex.Roblox.Thumbnails.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Knedlex.Roblox.Thumbnails.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.QueryParameters.Add(Knedlex.Roblox.Thumbnails.Api.Client.ClientUtils.ParameterToMultiMap("csv", "universeIds", universeIds));
            if (countPerUniverse != null)
            {
                localVarRequestOptions.QueryParameters.Add(Knedlex.Roblox.Thumbnails.Api.Client.ClientUtils.ParameterToMultiMap("", "countPerUniverse", countPerUniverse));
            }
            if (defaults != null)
            {
                localVarRequestOptions.QueryParameters.Add(Knedlex.Roblox.Thumbnails.Api.Client.ClientUtils.ParameterToMultiMap("", "defaults", defaults));
            }
            if (size != null)
            {
                localVarRequestOptions.QueryParameters.Add(Knedlex.Roblox.Thumbnails.Api.Client.ClientUtils.ParameterToMultiMap("", "size", size));
            }
            if (format != null)
            {
                localVarRequestOptions.QueryParameters.Add(Knedlex.Roblox.Thumbnails.Api.Client.ClientUtils.ParameterToMultiMap("", "format", format));
            }
            if (isCircular != null)
            {
                localVarRequestOptions.QueryParameters.Add(Knedlex.Roblox.Thumbnails.Api.Client.ClientUtils.ParameterToMultiMap("", "isCircular", isCircular));
            }

            localVarRequestOptions.Operation = "GamesApi.V1GamesMultigetThumbnailsGet";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<RobloxWebWebAPIModelsApiArrayResponseRobloxThumbnailsApiModelsUniverseThumbnailsResponse>("/v1/games/multiget/thumbnails", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("V1GamesMultigetThumbnailsGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Fetches game thumbnail URLs for a list of universes&#39; thumbnail ids. Ids that do not correspond to a valid thumbnail will be filtered out. 
        /// </summary>
        /// <exception cref="Knedlex.Roblox.Thumbnails.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="universeId"></param>
        /// <param name="thumbnailIds"></param>
        /// <param name="size">The thumbnail size, formatted widthxheight (optional, default to 768x432)</param>
        /// <param name="format">The thumbnail format (optional, default to Png)</param>
        /// <param name="isCircular">The circle thumbnail output parameter, true or false (optional, default to false)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>RobloxWebWebAPIModelsApiArrayResponseRobloxWebResponsesThumbnailsThumbnailResponse</returns>
        public RobloxWebWebAPIModelsApiArrayResponseRobloxWebResponsesThumbnailsThumbnailResponse V1GamesUniverseIdThumbnailsGet(long universeId, List<long> thumbnailIds, string size = default(string), string format = default(string), bool? isCircular = default(bool?), int operationIndex = 0)
        {
            Knedlex.Roblox.Thumbnails.Api.Client.ApiResponse<RobloxWebWebAPIModelsApiArrayResponseRobloxWebResponsesThumbnailsThumbnailResponse> localVarResponse = V1GamesUniverseIdThumbnailsGetWithHttpInfo(universeId, thumbnailIds, size, format, isCircular);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Fetches game thumbnail URLs for a list of universes&#39; thumbnail ids. Ids that do not correspond to a valid thumbnail will be filtered out. 
        /// </summary>
        /// <exception cref="Knedlex.Roblox.Thumbnails.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="universeId"></param>
        /// <param name="thumbnailIds"></param>
        /// <param name="size">The thumbnail size, formatted widthxheight (optional, default to 768x432)</param>
        /// <param name="format">The thumbnail format (optional, default to Png)</param>
        /// <param name="isCircular">The circle thumbnail output parameter, true or false (optional, default to false)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of RobloxWebWebAPIModelsApiArrayResponseRobloxWebResponsesThumbnailsThumbnailResponse</returns>
        public Knedlex.Roblox.Thumbnails.Api.Client.ApiResponse<RobloxWebWebAPIModelsApiArrayResponseRobloxWebResponsesThumbnailsThumbnailResponse> V1GamesUniverseIdThumbnailsGetWithHttpInfo(long universeId, List<long> thumbnailIds, string size = default(string), string format = default(string), bool? isCircular = default(bool?), int operationIndex = 0)
        {
            // verify the required parameter 'thumbnailIds' is set
            if (thumbnailIds == null)
            {
                throw new Knedlex.Roblox.Thumbnails.Api.Client.ApiException(400, "Missing required parameter 'thumbnailIds' when calling GamesApi->V1GamesUniverseIdThumbnailsGet");
            }

            Knedlex.Roblox.Thumbnails.Api.Client.RequestOptions localVarRequestOptions = new Knedlex.Roblox.Thumbnails.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "text/json"
            };

            var localVarContentType = Knedlex.Roblox.Thumbnails.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Knedlex.Roblox.Thumbnails.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("universeId", Knedlex.Roblox.Thumbnails.Api.Client.ClientUtils.ParameterToString(universeId)); // path parameter
            localVarRequestOptions.QueryParameters.Add(Knedlex.Roblox.Thumbnails.Api.Client.ClientUtils.ParameterToMultiMap("csv", "thumbnailIds", thumbnailIds));
            if (size != null)
            {
                localVarRequestOptions.QueryParameters.Add(Knedlex.Roblox.Thumbnails.Api.Client.ClientUtils.ParameterToMultiMap("", "size", size));
            }
            if (format != null)
            {
                localVarRequestOptions.QueryParameters.Add(Knedlex.Roblox.Thumbnails.Api.Client.ClientUtils.ParameterToMultiMap("", "format", format));
            }
            if (isCircular != null)
            {
                localVarRequestOptions.QueryParameters.Add(Knedlex.Roblox.Thumbnails.Api.Client.ClientUtils.ParameterToMultiMap("", "isCircular", isCircular));
            }

            localVarRequestOptions.Operation = "GamesApi.V1GamesUniverseIdThumbnailsGet";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<RobloxWebWebAPIModelsApiArrayResponseRobloxWebResponsesThumbnailsThumbnailResponse>("/v1/games/{universeId}/thumbnails", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("V1GamesUniverseIdThumbnailsGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Fetches game thumbnail URLs for a list of universes&#39; thumbnail ids. Ids that do not correspond to a valid thumbnail will be filtered out. 
        /// </summary>
        /// <exception cref="Knedlex.Roblox.Thumbnails.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="universeId"></param>
        /// <param name="thumbnailIds"></param>
        /// <param name="size">The thumbnail size, formatted widthxheight (optional, default to 768x432)</param>
        /// <param name="format">The thumbnail format (optional, default to Png)</param>
        /// <param name="isCircular">The circle thumbnail output parameter, true or false (optional, default to false)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of RobloxWebWebAPIModelsApiArrayResponseRobloxWebResponsesThumbnailsThumbnailResponse</returns>
        public async System.Threading.Tasks.Task<RobloxWebWebAPIModelsApiArrayResponseRobloxWebResponsesThumbnailsThumbnailResponse> V1GamesUniverseIdThumbnailsGetAsync(long universeId, List<long> thumbnailIds, string size = default(string), string format = default(string), bool? isCircular = default(bool?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Knedlex.Roblox.Thumbnails.Api.Client.ApiResponse<RobloxWebWebAPIModelsApiArrayResponseRobloxWebResponsesThumbnailsThumbnailResponse> localVarResponse = await V1GamesUniverseIdThumbnailsGetWithHttpInfoAsync(universeId, thumbnailIds, size, format, isCircular, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Fetches game thumbnail URLs for a list of universes&#39; thumbnail ids. Ids that do not correspond to a valid thumbnail will be filtered out. 
        /// </summary>
        /// <exception cref="Knedlex.Roblox.Thumbnails.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="universeId"></param>
        /// <param name="thumbnailIds"></param>
        /// <param name="size">The thumbnail size, formatted widthxheight (optional, default to 768x432)</param>
        /// <param name="format">The thumbnail format (optional, default to Png)</param>
        /// <param name="isCircular">The circle thumbnail output parameter, true or false (optional, default to false)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (RobloxWebWebAPIModelsApiArrayResponseRobloxWebResponsesThumbnailsThumbnailResponse)</returns>
        public async System.Threading.Tasks.Task<Knedlex.Roblox.Thumbnails.Api.Client.ApiResponse<RobloxWebWebAPIModelsApiArrayResponseRobloxWebResponsesThumbnailsThumbnailResponse>> V1GamesUniverseIdThumbnailsGetWithHttpInfoAsync(long universeId, List<long> thumbnailIds, string size = default(string), string format = default(string), bool? isCircular = default(bool?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'thumbnailIds' is set
            if (thumbnailIds == null)
            {
                throw new Knedlex.Roblox.Thumbnails.Api.Client.ApiException(400, "Missing required parameter 'thumbnailIds' when calling GamesApi->V1GamesUniverseIdThumbnailsGet");
            }


            Knedlex.Roblox.Thumbnails.Api.Client.RequestOptions localVarRequestOptions = new Knedlex.Roblox.Thumbnails.Api.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "text/json"
            };

            var localVarContentType = Knedlex.Roblox.Thumbnails.Api.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Knedlex.Roblox.Thumbnails.Api.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("universeId", Knedlex.Roblox.Thumbnails.Api.Client.ClientUtils.ParameterToString(universeId)); // path parameter
            localVarRequestOptions.QueryParameters.Add(Knedlex.Roblox.Thumbnails.Api.Client.ClientUtils.ParameterToMultiMap("csv", "thumbnailIds", thumbnailIds));
            if (size != null)
            {
                localVarRequestOptions.QueryParameters.Add(Knedlex.Roblox.Thumbnails.Api.Client.ClientUtils.ParameterToMultiMap("", "size", size));
            }
            if (format != null)
            {
                localVarRequestOptions.QueryParameters.Add(Knedlex.Roblox.Thumbnails.Api.Client.ClientUtils.ParameterToMultiMap("", "format", format));
            }
            if (isCircular != null)
            {
                localVarRequestOptions.QueryParameters.Add(Knedlex.Roblox.Thumbnails.Api.Client.ClientUtils.ParameterToMultiMap("", "isCircular", isCircular));
            }

            localVarRequestOptions.Operation = "GamesApi.V1GamesUniverseIdThumbnailsGet";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<RobloxWebWebAPIModelsApiArrayResponseRobloxWebResponsesThumbnailsThumbnailResponse>("/v1/games/{universeId}/thumbnails", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("V1GamesUniverseIdThumbnailsGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
