/*
 * Thumbnails Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Knedlex.Roblox.Thumbnails.Api.Client.OpenAPIDateConverter;

namespace Knedlex.Roblox.Thumbnails.Api.Model
{
    /// <summary>
    /// A response model for thumbnails which belong to a specific universe ID
    /// </summary>
    [DataContract(Name = "Roblox.Thumbnails.Api.Models.UniverseThumbnailsResponse")]
    public partial class RobloxThumbnailsApiModelsUniverseThumbnailsResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RobloxThumbnailsApiModelsUniverseThumbnailsResponse" /> class.
        /// </summary>
        /// <param name="universeId">Integer universe ID.</param>
        /// <param name="error">error.</param>
        /// <param name="thumbnails">An array of ThumbnailResponse objects.</param>
        public RobloxThumbnailsApiModelsUniverseThumbnailsResponse(long universeId = default(long), RobloxWebWebAPIModelsApiErrorModel error = default(RobloxWebWebAPIModelsApiErrorModel), List<RobloxWebResponsesThumbnailsThumbnailResponse> thumbnails = default(List<RobloxWebResponsesThumbnailsThumbnailResponse>))
        {
            this.UniverseId = universeId;
            this.Error = error;
            this.Thumbnails = thumbnails;
        }

        /// <summary>
        /// Integer universe ID
        /// </summary>
        /// <value>Integer universe ID</value>
        [DataMember(Name = "universeId", EmitDefaultValue = false)]
        public long UniverseId { get; set; }

        /// <summary>
        /// Gets or Sets Error
        /// </summary>
        [DataMember(Name = "error", EmitDefaultValue = false)]
        public RobloxWebWebAPIModelsApiErrorModel Error { get; set; }

        /// <summary>
        /// An array of ThumbnailResponse objects
        /// </summary>
        /// <value>An array of ThumbnailResponse objects</value>
        [DataMember(Name = "thumbnails", EmitDefaultValue = false)]
        public List<RobloxWebResponsesThumbnailsThumbnailResponse> Thumbnails { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RobloxThumbnailsApiModelsUniverseThumbnailsResponse {\n");
            sb.Append("  UniverseId: ").Append(UniverseId).Append("\n");
            sb.Append("  Error: ").Append(Error).Append("\n");
            sb.Append("  Thumbnails: ").Append(Thumbnails).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
