/*
 * Thumbnails Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.Roblox.Thumbnails.Api.Model;
using Knedlex.Roblox.Thumbnails.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.Roblox.Thumbnails.Api.Test.Model
{
    /// <summary>
    ///  Class for testing RobloxWebWebAPIModelsApiErrorModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RobloxWebWebAPIModelsApiErrorModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RobloxWebWebAPIModelsApiErrorModel
        //private RobloxWebWebAPIModelsApiErrorModel instance;

        public RobloxWebWebAPIModelsApiErrorModelTests()
        {
            // TODO uncomment below to create an instance of RobloxWebWebAPIModelsApiErrorModel
            //instance = new RobloxWebWebAPIModelsApiErrorModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RobloxWebWebAPIModelsApiErrorModel
        /// </summary>
        [Fact]
        public void RobloxWebWebAPIModelsApiErrorModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" RobloxWebWebAPIModelsApiErrorModel
            //Assert.IsType<RobloxWebWebAPIModelsApiErrorModel>(instance);
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'UserFacingMessage'
        /// </summary>
        [Fact]
        public void UserFacingMessageTest()
        {
            // TODO unit test for the property 'UserFacingMessage'
        }

        /// <summary>
        /// Test the property 'Field'
        /// </summary>
        [Fact]
        public void FieldTest()
        {
            // TODO unit test for the property 'Field'
        }

        /// <summary>
        /// Test the property 'FieldData'
        /// </summary>
        [Fact]
        public void FieldDataTest()
        {
            // TODO unit test for the property 'FieldData'
        }
    }
}
