/*
 * Thumbnails Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Knedlex.Roblox.Thumbnails.Api.Model;
using Knedlex.Roblox.Thumbnails.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Knedlex.Roblox.Thumbnails.Api.Test.Model
{
    /// <summary>
    ///  Class for testing RobloxThumbsImageParameters
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RobloxThumbsImageParametersTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RobloxThumbsImageParameters
        //private RobloxThumbsImageParameters instance;

        public RobloxThumbsImageParametersTests()
        {
            // TODO uncomment below to create an instance of RobloxThumbsImageParameters
            //instance = new RobloxThumbsImageParameters();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RobloxThumbsImageParameters
        /// </summary>
        [Fact]
        public void RobloxThumbsImageParametersInstanceTest()
        {
            // TODO uncomment below to test "IsType" RobloxThumbsImageParameters
            //Assert.IsType<RobloxThumbsImageParameters>(instance);
        }

        /// <summary>
        /// Test the property 'Width'
        /// </summary>
        [Fact]
        public void WidthTest()
        {
            // TODO unit test for the property 'Width'
        }

        /// <summary>
        /// Test the property 'Height'
        /// </summary>
        [Fact]
        public void HeightTest()
        {
            // TODO unit test for the property 'Height'
        }

        /// <summary>
        /// Test the property 'Format'
        /// </summary>
        [Fact]
        public void FormatTest()
        {
            // TODO unit test for the property 'Format'
        }

        /// <summary>
        /// Test the property 'IsCircular'
        /// </summary>
        [Fact]
        public void IsCircularTest()
        {
            // TODO unit test for the property 'IsCircular'
        }

        /// <summary>
        /// Test the property 'FileExtension'
        /// </summary>
        [Fact]
        public void FileExtensionTest()
        {
            // TODO unit test for the property 'FileExtension'
        }

        /// <summary>
        /// Test the property 'MimeType'
        /// </summary>
        [Fact]
        public void MimeTypeTest()
        {
            // TODO unit test for the property 'MimeType'
        }
    }
}
