/*
 * Thumbnails Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Knedlex.Roblox.Thumbnails.Api.Client;
using Knedlex.Roblox.Thumbnails.Api.Api;
// uncomment below to import models
//using Knedlex.Roblox.Thumbnails.Api.Model;

namespace Knedlex.Roblox.Thumbnails.Api.Test.Api
{
    /// <summary>
    ///  Class for testing AssetsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AssetsApiTests : IDisposable
    {
        private AssetsApi instance;

        public AssetsApiTests()
        {
            instance = new AssetsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AssetsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' AssetsApi
            //Assert.IsType<AssetsApi>(instance);
        }

        /// <summary>
        /// Test V1AssetThumbnailAnimatedGet
        /// </summary>
        [Fact]
        public void V1AssetThumbnailAnimatedGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long assetId = null;
            //long? robloxPlaceId = null;
            //var response = instance.V1AssetThumbnailAnimatedGet(assetId, robloxPlaceId);
            //Assert.IsType<RobloxWebResponsesThumbnailsThumbnailResponse>(response);
        }

        /// <summary>
        /// Test V1AssetsGet
        /// </summary>
        [Fact]
        public void V1AssetsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<long> assetIds = null;
            //long? robloxPlaceId = null;
            //string returnPolicy = null;
            //string size = null;
            //string format = null;
            //bool? isCircular = null;
            //var response = instance.V1AssetsGet(assetIds, robloxPlaceId, returnPolicy, size, format, isCircular);
            //Assert.IsType<RobloxWebWebAPIModelsApiArrayResponseRobloxWebResponsesThumbnailsThumbnailResponse>(response);
        }

        /// <summary>
        /// Test V1AssetsThumbnail3dGet
        /// </summary>
        [Fact]
        public void V1AssetsThumbnail3dGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long assetId = null;
            //long? robloxPlaceId = null;
            //var response = instance.V1AssetsThumbnail3dGet(assetId, robloxPlaceId);
            //Assert.IsType<RobloxWebResponsesThumbnailsThumbnailResponse>(response);
        }
    }
}
