/*
 * Thumbnails Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Knedlex.Roblox.Thumbnails.Api.Client;
using Knedlex.Roblox.Thumbnails.Api.Api;
// uncomment below to import models
//using Knedlex.Roblox.Thumbnails.Api.Model;

namespace Knedlex.Roblox.Thumbnails.Api.Test.Api
{
    /// <summary>
    ///  Class for testing DeveloperProductsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class DeveloperProductsApiTests : IDisposable
    {
        private DeveloperProductsApi instance;

        public DeveloperProductsApiTests()
        {
            instance = new DeveloperProductsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DeveloperProductsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' DeveloperProductsApi
            //Assert.IsType<DeveloperProductsApi>(instance);
        }

        /// <summary>
        /// Test V1DeveloperProductsIconsGet
        /// </summary>
        [Fact]
        public void V1DeveloperProductsIconsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<long> developerProductIds = null;
            //string size = null;
            //string format = null;
            //bool? isCircular = null;
            //var response = instance.V1DeveloperProductsIconsGet(developerProductIds, size, format, isCircular);
            //Assert.IsType<RobloxWebWebAPIModelsApiArrayResponseRobloxWebResponsesThumbnailsThumbnailResponse>(response);
        }
    }
}
