/*
 * Thumbnails Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Knedlex.Roblox.Thumbnails.ApiV1.Client;
using Knedlex.Roblox.Thumbnails.ApiV1.Api;
// uncomment below to import models
//using Knedlex.Roblox.Thumbnails.ApiV1.Model;

namespace Knedlex.Roblox.Thumbnails.ApiV1.Test.Api
{
    /// <summary>
    ///  Class for testing AvatarApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AvatarApiTests : IDisposable
    {
        private AvatarApi instance;

        public AvatarApiTests()
        {
            instance = new AvatarApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AvatarApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' AvatarApi
            //Assert.IsType<AvatarApi>(instance);
        }

        /// <summary>
        /// Test V1UsersAvatar3dGet
        /// </summary>
        [Fact]
        public void V1UsersAvatar3dGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long userId = null;
            //var response = instance.V1UsersAvatar3dGet(userId);
            //Assert.IsType<RobloxWebResponsesThumbnailsThumbnailResponse>(response);
        }

        /// <summary>
        /// Test V1UsersAvatarBustGet
        /// </summary>
        [Fact]
        public void V1UsersAvatarBustGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<long> userIds = null;
            //string size = null;
            //string format = null;
            //bool? isCircular = null;
            //var response = instance.V1UsersAvatarBustGet(userIds, size, format, isCircular);
            //Assert.IsType<RobloxWebWebAPIModelsApiArrayResponseRobloxWebResponsesThumbnailsThumbnailResponse>(response);
        }

        /// <summary>
        /// Test V1UsersAvatarGet
        /// </summary>
        [Fact]
        public void V1UsersAvatarGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<long> userIds = null;
            //string size = null;
            //string format = null;
            //bool? isCircular = null;
            //var response = instance.V1UsersAvatarGet(userIds, size, format, isCircular);
            //Assert.IsType<RobloxWebWebAPIModelsApiArrayResponseRobloxWebResponsesThumbnailsThumbnailResponse>(response);
        }

        /// <summary>
        /// Test V1UsersAvatarHeadshotGet
        /// </summary>
        [Fact]
        public void V1UsersAvatarHeadshotGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<long> userIds = null;
            //string size = null;
            //string format = null;
            //bool? isCircular = null;
            //var response = instance.V1UsersAvatarHeadshotGet(userIds, size, format, isCircular);
            //Assert.IsType<RobloxWebWebAPIModelsApiArrayResponseRobloxWebResponsesThumbnailsThumbnailResponse>(response);
        }
    }
}
