/*
 * Thumbnails Api v1
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Knedlex.Roblox.Thumbnails.ApiV1.Client;
using Knedlex.Roblox.Thumbnails.ApiV1.Api;
// uncomment below to import models
//using Knedlex.Roblox.Thumbnails.ApiV1.Model;

namespace Knedlex.Roblox.Thumbnails.ApiV1.Test.Api
{
    /// <summary>
    ///  Class for testing GroupEmblemApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class GroupEmblemApiTests : IDisposable
    {
        private GroupEmblemApi instance;

        public GroupEmblemApiTests()
        {
            instance = new GroupEmblemApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GroupEmblemApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' GroupEmblemApi
            //Assert.IsType<GroupEmblemApi>(instance);
        }

        /// <summary>
        /// Test V1GroupsIconsGet
        /// </summary>
        [Fact]
        public void V1GroupsIconsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<long> groupIds = null;
            //string size = null;
            //string format = null;
            //bool? isCircular = null;
            //var response = instance.V1GroupsIconsGet(groupIds, size, format, isCircular);
            //Assert.IsType<RobloxWebWebAPIModelsApiArrayResponseRobloxWebResponsesThumbnailsThumbnailResponse>(response);
        }
    }
}
